### ISSUE TITLE
Documentation: Create a simple documentation

### ISSUE THREAD

**Issue by karlcow** [karlcow/shoki#1]
Create a simple documentation for allowing others in the team to use it.
* How to use it
* How to deploy it.

**Comment by miketaylr** [comment]
I tried to generate minutes from https://webcompat-meet.herokuapp.com/s/H1ZIgOtHm# like so:

```python
python shoki.py create --location https://webcompat-meet.herokuapp.com/s/H1ZIgOtHm#
Traceback (most recent call last):
  File "shoki.py", line 67, in <module>
    main()
  File "shoki.py", line 59, in main
    content = create(args)
  File "shoki.py", line 46, in create
    return datacore.create_minutes(**parsed_args)
  File "/Users/mitaylor/dev/shoki/shoki/datacore.py", line 42, in create_minutes
    minutes = formatter.convert(minutes_as_data(raw_text), out_format)
  File "/Users/mitaylor/dev/shoki/shoki/datacore.py", line 20, in minutes_as_data
    meta = parsing.meta_headers(text)
  File "/Users/mitaylor/dev/shoki/shoki/parsing.py", line 121, in meta_headers
    meta_key, meta_value = line.split(":", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

It did not work. :)

**Comment by karlcow** [comment]
@miketaylr yes because you need the text version of the document.
which in this case would be https://webcompat-meet.herokuapp.com/0CMnUyYMSBaQJQ97Yxc8Ww/download. `download` is the important bit. I should probably gracefully verify the content-type and tell people, that we need a text version of the document.

This is a strange version of the link https://webcompat-meet.herokuapp.com/s/H1ZIgOtHm 
If I remove the s I get redirected to `Location: /0CMnUyYMSBaQJQ97Yxc8Ww`

**Comment by karlcow** [comment]
Created #9 for addressing the wrong content-type.
