### ISSUE TITLE
Should parsing stop if TODO is incomplete.

### ISSUE THREAD

**Issue by karlcow** [karlcow/shoki#3]
Currently TODO is working this way

```
TODO: Saint-Exupéry to write Le Petit Prince 2, the sequel. 2020-04-05
```

but will fail if 

```
TODO: write Le Petit Prince 2, the sequel. 2020-04-05
```

aka no owner and no ` to `

Instead of breaking the parsing and the full code. We could record it as an error with a notification to fix it.

**Comment by karlcow** [comment]
```→ python3 shoki.py create --location http://example.org/tmp/webcompat.txt
Traceback (most recent call last):
  File "shoki.py", line 59, in <module>
    main()
  File "shoki.py", line 51, in main
    content = create(args)
  File "shoki.py", line 38, in create
    return datacore.create_minutes(**parsed_args)
  File "/Users/karl/code/shoki/shoki/datacore.py", line 43, in create_minutes
    minutes = formatter.convert(minutes_as_data(raw_text), out_format)
  File "/Users/karl/code/shoki/shoki/datacore.py", line 32, in minutes_as_data
    block['prose'])
  File "/Users/karl/code/shoki/shoki/parsing.py", line 90, in extract_prose
    voice = extract_todo(speaker, text)
  File "/Users/karl/code/shoki/shoki/parsing.py", line 133, in extract_todo
    owner, action_line = text.split(' to ', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

with @miketaylr action item written by thomas :)
shoki really needs to be more resilient on these.

```
TODO: Mike, to add
```

**Comment by miketaylr** [comment]
> We could record it as an error with a notification to fix it.

👍
